applicationTitle: Camp Camel TV Service
noise: 0.2
shadowMask: aperture-grille
bezel: flat
startUnmuted: true
osd:
  theme: digital

refs:
  mcvc:
    backgroundAudio: https://cmd-hue.github.io/camel/outage/music.pls
    backgroundAudioOptions:
     shufflePlaylist: true

defaultChannel: 1
noSignalContent: 
 image: offline.png
 ref: mcvc

channels:

- number: 1 # As mentioned previously you can declare channels in any order; they'll be arranged when you begin.
  name: Program Guide
  abbr: GUIDE
  title: Prevue Guide
  noise: 0.1
  ref: mcvc
  v-split: # Program guides are traditionally split in half; the top half is advertising and the lower half is the guide data. We use the v-split layout which defines two components, A and B.
    a: # A is the top part. See: https://greenhillplaza.notion.site/Layouts-728ab1198d4049de8f4b9a4ff6b31efe?pvs=4
      loop:
      - slideshow:
          duration: 3.14
          images:
            - ./ads/catdog-dvd-request.png
            - ./ads/cnplus.png
            - ./ads/vidtape.png
            - ./ads/lazioh.png
            - ./ads/videofeat.png
            - ./ads/beeco.png
            - ./ads/windowsfamily.png
    b: # B is the bottom part
      guide: # Program guides read the current channel lineup to reconstruct listings based off channel numbers, title and description. https://greenhillplaza.notion.site/Program-Guides-46e80919a3754efa9769f74dd00946fe?pvs=4
        logo: ./logo.svg # Logo to show at the top of the guide
        alerts: # "Alerts" that show up at certain positions in the guide.
          - position: 12 # The channel to show the alert after. Doesn't need to be a real channel.
            text: |
              If any channels aren't working, contact a staffmember.
          - position: 100
            text: | # You can define text over multiple lines but it'll be compressed to a single line.
              Warning: Piracy is a crime and could get you a few years in prison. Do NOT Do It.

- number: 2
  name: Cartoon Network Plus
  title: Cartoon Network Plus
  abbr: CNPS
  video: https://watch.mistweather.com/hls/cnplus/playlist.m3u8

- number: 3
  name: allo allo
  title: allo allo
  abbr: alo
  video: https://archive.org/download/allo-allo/01%20-%20Allo%20Allo%20S1E00%20-%20The%20British%20Are%20Coming%20%5BPilot%5D.mp4

- number: 4
  name: NLEC TV
  abbr: NLTV
  title: NLEC TV
  icon: https://files.snappages.site/4Z33KD/assets/favicon.png
  video: https://622e9a7089364.streamlock.net/live/ngrp:24-2_all/playlist.m3u8


- number: 5
  name: Aquarium
  title:  Aquarium
  abbr: AQUA
  iframe: 
   src: https://webglsamples.org/aquarium/aquarium.html
   allowInteraction: false

- number: 6
  name: Random
  title:  Random
  abbr: RND
  description: random pictures
  image: https://loremflickr.com/640/360?random=1

- number: 7
  name: WeatherScan
  title: WeatherScan
  video: https://watch.mistweather.com/hls/asrn2/playlist.m3u8

- number: 8
  name: Clock
  title:  Current Time
  abbr: CLK
  iframe: 
   src: https://cmd-hue.github.io/camel/clock/index.html
   allowInteraction: false

- number: 9
  name: Camp Previews
  title:  Camp Previews
  abbr: PRE
  video: https://cmd-hue.github.io/camel/shows/playlist.pls

- number: 10
  name: Music Voice
  abbr: MCV
  ref: mcvc
  daily-schedule:
    content:
    - startTime: "19:00" 
      endTime: "06:00"
      image: 
        src: https://cmd-hue.github.io/camel/musicvoice_nightslide.png
    - startTime: "6:00"
      endTime: "19:00"
      image:
        src: https://cmd-hue.github.io/camel/musicvoice_slide.png